### ISSUE TITLE
BadStatusLine Error

### ISSUE THREAD

**Issue by jfledvin** [iBaa/PlexConnect#368]
Hi,

Just did a fresh git clone, copied over my trailers certs to assets/certificates, trying to access PlexConnect causes this:

Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/PlexConnect/PlexAPI.py", line 408, in getXMLFromPMSToQueue
    XML = getXMLFromPMS(PMS['baseURL'],PMS['path'],PMS['options'],PMS['token'])
  File "/root/PlexConnect/PlexAPI.py", line 377, in getXMLFromPMS
    response = urllib2.urlopen(request, timeout=20)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1131, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

Interface shows up, however no servers/content appears. Could be a weird config on my end. 
Running: Python 2.7.10 on Debian Testing 9.0

**Comment by jfledvin** [comment]
Scratch that, looks like Shared Libraries works as does the Settings panel. The others, when switched to, cause that error with no content appearing.

**Comment by jfledvin** [comment]
Changed 'Secure connections " from "Required" to "Preferred" solved the issue.
