### ISSUE TITLE
Internel server error reported

### ISSUE THREAD

**Issue by RobinQu** [iBaa/PlexConnect#394]
It was streaming video as normal, but suddenly AppleTV said trailer app is not available. Restarting AppleTV didn't help either.

I have checked network connection and server status, which turned out to be okay.

Then I opened PlexConnect.log and found something suspicious:

```
19:31:46 WebServer: Internal Server Error:
Traceback (most recent call last):
  File "/Applications/PlexConnect/WebServer.py", line 229, in do_GET
    XML = XMLConverter.XML_PMS2aTV(PMSaddress, self.path + query, options)
  File "/Applications/PlexConnect/XMLConverter.py", line 376, in XML_PMS2aTV
    PMS = PlexAPI.getXMLFromPMS(PMS_baseURL, path, options, auth_token, enableGzip)
  File "/Applications/PlexConnect/PlexAPI.py", line 402, in getXMLFromPMS
    response = urllib2.urlopen(request, timeout=20)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 423, in open
    protocol = req.get_type()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /library/metadata/1156

19:31:49 WebServer: Internal Server Error:
Traceback (most recent call last):
  File "/Applications/PlexConnect/WebServer.py", line 229, in do_GET
    XML = XMLConverter.XML_PMS2aTV(PMSaddress, self.path + query, options)
  File "/Applications/PlexConnect/XMLConverter.py", line 376, in XML_PMS2aTV
    PMS = PlexAPI.getXMLFromPMS(PMS_baseURL, path, options, auth_token, enableGzip)
  File "/Applications/PlexConnect/PlexAPI.py", line 402, in getXMLFromPMS
    response = urllib2.urlopen(request, timeout=20)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 423, in open
    protocol = req.get_type()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /library/sections/3

19:31:54 PlexAPI: ***
19:31:54 PlexAPI: PlexGDM - looking up Plex Media Server
19:31:54 PlexAPI: ***
19:31:55 PlexAPI: GDM: Servers discovered: 1
19:31:55 PlexAPI: Servers (local, plex.tv, MyPlex): 2
19:32:08 WebServer: File Not Found:
Traceback (most recent call last):
  File "/Applications/PlexConnect/WebServer.py", line 213, in do_GET
    f = open(sys.path[0] + sep + "assets" + self.path, "rb")
IOError: [Errno 2] No such file or directory: '/Applications/PlexConnect/assets/thumbnails/MediaBadges/flac.png'

```

I thought PlexConnect should have died, but it was not the truth.

```
$ sudo launchctl list |grep plex
84  0   com.plex.plexconnect.bash
```

BTW I am using commit 1d4e285214fd96281e81007e43c7600e0d12f935 on OSX 10.11.1.

**Comment by iBaa** [comment]
Need more data - logs from a couple of seconds before the issue appeared. And with loglevel="High"...

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
