### ISSUE TITLE
Not working since yesterday

### ISSUE THREAD

**Issue by bob1321** [iBaa/PlexConnect#426]
08:38:02 WebServer: serving .xml: /
08:38:02 PlexAPI: ***
08:38:02 PlexAPI: poke plex.tv - request Plex Media Server list
08:38:02 PlexAPI: ***
08:38:23 PlexAPI: No Response from Plex Media Server
08:38:23 PlexAPI: We failed to reach a server. Reason: timed out
08:38:23 PlexAPI: Traceback:
Traceback (most recent call last):
  File "C:\Users\Pascal-Chambre\Desktop\PlexConnect-master\PlexAPI.py", line 406, in getXMLFromPMS
    response = urllib2.urlopen(request, timeout=20)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1240, in https_open
    context=self._context)
  File "C:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>

**Comment by iBaa** [comment]
Please post in the Plex forums, adding more information. Like OS, environment, ... some of that info would be there with a full log and "loglevel=High". https://forums.plex.tv/discussion/69410/read-before-posting#latest
