### ISSUE TITLE
Syntax Error During Startup

### ISSUE THREAD

**Issue by deathpixjunk** [iBaa/PlexConnect#430]
```
Machine:PlexConnect $ sudo ./PlexConnect.py
Password:
Traceback (most recent call last):
  File "./PlexConnect.py", line 19, in <module>
    import DNSServer, WebServer
  File "/Users/myuser/PlexConnect/DNSServer.py", line 116
    print "ID {0:04x}".format((ord(paket[0])<<8)+ord(paket[1]))
                     ^
SyntaxError: invalid syntax
```

Python version is 2.7.10_2.

**Comment by iBaa** [comment]
Using python 3?
PlexConnect really only works on 2.7.x, best with x>6 or 7 or something.
