### ISSUE TITLE
PlexGDM [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by PierreBrisorgueil** [iBaa/PlexConnect#433]
```
19:02:37 WebServer: File Not Found:
Traceback (most recent call last):
  File "/home/pierre/Scripts/PlexConnect/WebServer.py", line 229, in do_GET
    XML = XMLConverter.XML_PMS2aTV(PMSaddress, self.path + query, options)
  File "/home/pierre/Scripts/PlexConnect/XMLConverter.py", line 317, in XML_PMS2aTV
    PlexAPI.discoverPMS(UDID, g_param['CSettings'], g_param['IP_self'], tokenDict)
  File "/home/pierre/Scripts/PlexConnect/PlexAPI.py", line 272, in discoverPMS
    PMS_list = PlexGDM()
  File "/home/pierre/Scripts/PlexConnect/PlexAPI.py", line 161, in PlexGDM
    GDM.sendto(Msg_PlexGDM, (IP_PlexGDM, Port_PlexGDM))
error: [Errno 1] Operation not permitted
```

Hello, can you give me some help on this ? 

I specified my fix iP in Settings.cfg, i'm not a expert in python, is it an iptables issue ? PlexmediaServer and plex connect are on the same server. 

Ubuntu, python 2.7.10, clone today

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
