### ISSUE TITLE
Plex Server Works, but not plexconnect

### ISSUE THREAD

**Issue by cferron** [iBaa/PlexConnect#435]
20:06:26 PlexAPI: Servers (local, plex.tv, MyPlex): 1
20:07:01 PlexAPI: ***
20:07:01 PlexAPI: poke plex.tv - request Plex Media Server list
20:07:01 PlexAPI: ***
20:07:02 PlexAPI: No Response from Plex Media Server
20:07:02 PlexAPI: We failed to reach a server. Reason: EOF occurred in violation of protocol (_ssl.c:590)
20:07:02 PlexAPI: Traceback:
Traceback (most recent call last):
  File "/Applications/PlexConnect/PlexAPI.py", line 426, in getXMLFromPMS
    response = urllib2.urlopen(request, timeout=20)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)>

**Comment by henrymazza** [comment]
+1

**Comment by cferron** [comment]
Ok, this seem to have been fix by Plex team on their side for some reason...

You can close as I don't have this behavior anymore...

**Comment by iBaa** [comment]
Close per request. :-D
