### ISSUE TITLE
Plexconnect not displaying media on ATV 3 I am using Server 2012 R2

### ISSUE THREAD

**Issue by BanditBev** [iBaa/PlexConnect#444]
Hi, I am not seeing the content on the ATV even though I can access the Plex Connect app. I am getting the following error below:

21:03:03 PlexAPI: No Response from Plex Media Server
21:03:03 PlexAPI: We failed to reach a server. Reason: ('_ssl.c:574: The handsha
ke operation timed out',)
21:03:03 PlexAPI: Traceback:
Traceback (most recent call last):
  File "C:\Program Files (x86)\PlexConnect-master\PlexAPI.py", line 432, in getX
MLFromPMS
    response = urllib2.urlopen(request, timeout=20)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1241, in https_open
    context=self._context)
  File "C:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error ('_ssl.c:574: The handshake operation timed out',)>

21:03:03 PlexAPI: No Response from Plex Media Server
21:03:03 PlexAPI: We failed to reach a server. Reason: timed out
21:03:03 PlexAPI: Traceback:
Traceback (most recent call last):
  File "C:\Program Files (x86)\PlexConnect-master\PlexAPI.py", line 432, in getX
MLFromPMS
    response = urllib2.urlopen(request, timeout=20)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1241, in https_open
    context=self._context)
  File "C:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>

21:03:03 PlexAPI: Servers (local, plex.tv, MyPlex): 1
21:03:03 WebServer: serving .xml: /PlexConnect.xml
21:03:04 WebServer: serving /js/utils.js
21:03:04 WebServer: serving /js/handlePlexConnectNavbar.js
21:03:04 WebServer: serving .xml: /library/sections
21:03:04 WebServer: serving /js/utils.js
21:03:04 WebServer: serving /js/sectionHoldSelect.js
21:04:54 DNSServer: DNS request received!
21:04:55 DNSServer: Source: ('192.168.1.73', 64404)
21:04:55 DNSServer: Domain: e673.e9.akamaiedge.net
21:04:55 DNSServer: _**forward request
21:04:55 DNSServer: -> DNS response from higher level
21:04:55 DNSServer: DNS request received!
21:04:55 DNSServer: Source: ('192.168.1.73', 60039)
21:04:55 DNSServer: Domain: upp.itunes.apple.com
21:04:55 DNSServer: *_*forward request
21:04:55 DNSServer: -> DNS response from higher level

Thankyou in advance

**Comment by gipasoft** [comment]
Same on QNAP TS-469 Pro

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
