### ISSUE TITLE
Issue with plexconnect

### ISSUE THREAD

**Issue by ElBrad** [iBaa/PlexConnect#451]
Hi,

I am attempting to install plexconnect again after not using it for a few months. However I am facing the following output from the console.

```
01:41:49 PlexConnect: ***
01:41:49 PlexConnect: PlexConnect
01:41:49 PlexConnect: Press CTRL-C to shut down.
01:41:49 PlexConnect: ***
01:41:49 PlexConnect: started: 01:41:49
01:41:49 PlexConnect: Version: 0.5-dev-110616
01:41:49 PlexConnect: Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:2
2) [MSC v.1500 32 bit (Intel)]
01:41:49 PlexConnect: Host OS: win32
01:41:49 PlexConnect: PILBackgrounds: Is PIL installed? False
01:41:49 PlexConnect: IP_self (from settings): 192.168.2.123
01:41:50 DNSServer: started: 01:41:50
01:41:50 DNSServer: ***
01:41:50 DNSServer: DNSServer: Serving DNS on 192.168.2.123 port 53.
01:41:50 DNSServer: intercept: ['trailers.apple.com'] => 192.168.2.123
01:41:50 DNSServer: restrain: ['mesu.apple.com', 'appldnld.apple.com', 'appldnld
.apple.com.edgesuite.net'] => 127.0.0.1
01:41:50 DNSServer: forward other to higher level DNS: 8.8.8.8
01:41:50 DNSServer: ***
01:41:50 WebServer: started: 01:41:50
01:41:50 WebServer: started: 01:41:500
1:41:50 WebServer: ***
01:41:50 WebServer: WebServer: Serving HTTP on 192.168.2.123 port 80.
01:41:50 WebServer: ***
01:41:50 WebServer: ***
01:41:50 WebServer: WebServer: Serving HTTPS on 192.168.2.123 port 443.
01:41:50 WebServer: ***
01:41:57 DNSServer: DNS request received!
01:41:57 DNSServer: Source: ('192.168.2.115', 61799)
01:41:57 DNSServer: Domain: trailers.apple.com
01:41:57 DNSServer: ***intercept request
01:41:57 DNSServer: -> DNS response: 192.168.2.123
01:41:57 WebServer: serving /js/application.js
01:41:57 WebServer: serving .xml: /
01:41:57 PlexAPI: ***
01:41:57 PlexAPI: poke plex.tv - request Plex Media Server list
01:41:57 PlexAPI: ***
01:41:58 PlexAPI: poke Media Server (79b4597acd107a50822e49208d5953f71b5140cb) a
t https://192-168-122-171.fc585011b8674acfa6e586726134ad46.plex.direct:32400
01:41:58 PlexAPI: poke Media Server (79b4597acd107a50822e49208d5953f71b5140cb) a
t https://192-168-2-123.fc585011b8674acfa6e586726134ad46.plex.direct:32400
01:41:58 PlexAPI: No Response from Plex Media Server
01:41:5801:41:58  PlexAPI: We failed to reach a server. Reason: [Errno 11004] ge
taddrinfo failed
PlexAPI: No Response from Plex Media Server
01:41:58 PlexAPI: We failed to reach a server. Reason: [Errno 11004] getaddrinfo
 failed
01:41:58 PlexAPI: Traceback:
Traceback (most recent call last):
  File "C:\Program Files (x86)\PlexConnect\PlexAPI.py", line 433, in getXMLFromP
MS
    response = urllib2.urlopen(request, timeout=20)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1241, in https_open
    context=self._context)
  File "C:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>

01:41:58 PlexAPI: Traceback:
Traceback (most recent call last):
  File "C:\Program Files (x86)\PlexConnect\PlexAPI.py", line 433, in getXMLFromP
MS
    response = urllib2.urlopen(request, timeout=20)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1241, in https_open
    context=self._context)
  File "C:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>

01:41:58 PlexAPI: Servers (local, plex.tv, MyPlex): 1
01:41:58 WebServer: serving .xml: /PlexConnect.xml
01:41:58 WebServer: serving /js/utils.js
01:41:59 WebServer: serving /js/handlePlexConnectNavbar.js
01:41:59 WebServer: serving .xml: /library/sections
01:41:59 WebServer: serving /js/utils.js
01:41:59 WebServer: serving /js/sectionHoldSelect.js
```

My settings.cfg looks like this:

```
[PlexConnect]
enable_plexgdm = False
ip_pms = 192.168.2.123
port_pms = 32400
enable_dnsserver = True
port_dnsserver = 53
ip_dnsmaster = 8.8.8.8
prevent_atv_update = True
enable_plexconnect_autodetect = False
ip_plexconnect = 192.168.2.123
hosttointercept = trailers.apple.com
port_webserver = 80
enable_webserver_ssl = True
port_ssl = 443
certfile = ./assets/certificates/trailers.pem
allow_gzip_atv = False
allow_gzip_pmslocal = False
allow_gzip_pmsremote = True
loglevel = Normal
logpath = .
```

Anyone have any ideas? I've tried removing the PIN from Plex config, disabling my firewall, logged in on both plex in Trailers and on the web interface. No joy.

**Comment by ElBrad** [comment]
Quick fix solution:

It seems to be the problem is happening because I have 2 network interfaces. I disabled one of the interfaces (the one the plex server WASN'T running on) and it worked. I'm not sure how you would get around this? Prompt the user for the interface they wish to use if multiple are detected?

**Comment by ElBrad** [comment]
Even with this workaround it seems I still cannot play media though, the library shows up but no coverart and errors when attempting to play

**Comment by doho121** [comment]
I just logged a similar issue - when you are connected the same network as the AppleTV can you web browser to 192.168.2.123:32400? Take a look at my issue logged above yours and see if they are related.

**Comment by haxcop** [comment]
@ElBrad HI, Well try this , I'm assuming your router is 192.168.192.1

[PlexConnect]
enable_plexgdm = False
ip_pms = 192.168.2.123
port_pms = 32400
enable_dnsserver = True
port_dnsserver = 53
ip_dnsmaster = 192.168.192.1
prevent_atv_update = True
enable_plexconnect_autodetect = False
ip_plexconnect = 192.168.2.123
hosttointercept = trailers.apple.com
port_webserver = 80
enable_webserver_ssl = True
port_ssl = 443
certfile = ./assets/certificates/trailers.pem
allow_gzip_atv = False
allow_gzip_pmslocal = False
allow_gzip_pmsremote = True
loglevel = Normal
logpath = .

Otherwise please supply your network set up including the interfaces and pms without public ip...

**Comment by moodyblue** [comment]
PMS does not supports 2 NIC's for the same LAN unless you are using LACP. This is not a PlexConnect problem, so please close this issue.
