### ISSUE TITLE
Error from PILBackgrounds

### ISSUE THREAD

**Issue by Fish2** [iBaa/PlexConnect#491]
I think its from a PIL update

> Before Pillow 4.2.0, attempting to save an RGBA image as JPEG would discard the alpha channel. From Pillow 3.4.0, a deprecation warning was shown. From Pillow 4.2.0, the deprecation warning is removed and an IOError is raised.

from [http://pillow.readthedocs.io/en/4.2.x/releasenotes/4.2.0.html](http://pillow.readthedocs.io/en/4.2.x/releasenotes/4.2.0.html)

```
PILBackgrounds: Error - Failed to generate background image.
Traceback (most recent call last):
  File "/opt/plexconnect/PILBackgrounds.py", line 101, in generate
    background.paste(layer, ( 0, 0), layer)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1328, in paste
    self.im.paste(im, box, mask.im)
ValueError: bad transparency mask
```

**Comment by Fish2** [comment]
fixed with https://github.com/Fish2/PlexConnect/commit/dcb8bc7c8de103bdd71f3668a911f3219a26fca1
