### ISSUE TITLE
Plexconnect wont start

### ISSUE THREAD

**Issue by projay11** [iBaa/PlexConnect#493]
Traceback (most recent call last):
  File "C:\Users\Hades\Desktop\PlexConnect-master\PlexConnect.py", line 19, in <module>
    import DNSServer, WebServer
  File "C:\Users\Hades\Desktop\PlexConnect-master\DNSServer.py", line 116
    print "ID {0:04x}".format((ord(paket[0])<<8)+ord(paket[1]))

**Comment by moodyblue** [comment]
Help requests should be posted in the forum

https://forums.plex.tv/categories/appletv-plexconnect
