### ISSUE TITLE
No Plex Library Sections Available

### ISSUE THREAD

**Issue by gugeswe** [iBaa/PlexConnect#507]
Does it have anything to do with authentication?

Here is Settings.cfg
```
[PlexConnect]
enable_plexgdm = False
ip_pms = 192.168.1.29
port_pms = 32400
enable_dnsserver = True
port_dnsserver = 53
ip_dnsmaster = 192.168.1.1
prevent_atv_update = True
enable_plexconnect_autodetect = True
ip_plexconnect = 192.168.1.29
hosttointercept = trailers.apple.com
port_webserver = 80
enable_webserver_ssl = True
port_ssl = 443
certfile = ./assets/certificates/trailers.pem
allow_gzip_atv = False
allow_gzip_pmslocal = False
allow_gzip_pmsremote = True
loglevel = Normal
logpath = .
```

Here is the log:

```
Dec 03,2017 16:11:26 PlexConnect: Started
Dec 03,2017 16:11:26 PlexConnect: Version: 0.5-dev-161017
Dec 03,2017 16:11:26 PlexConnect: Python: 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0]
Dec 03,2017 16:11:26 PlexConnect: Host OS: linux2
Dec 03,2017 16:11:26 PlexConnect: PILBackgrounds: Is PIL installed? False
Dec 03,2017 16:11:26 PlexConnect: IP_self: 192.168.1.29
Dec 03,2017 16:11:26 DNSServer: Started
Dec 03,2017 16:11:26 DNSServer: ***
Dec 03,2017 16:11:26 DNSServer: DNSServer: Serving DNS on 192.168.1.29 port 53.
Dec 03,2017 16:11:26 DNSServer: ***
Dec 03,2017 16:11:27 WebServer: Started
Dec 03,2017 16:11:27 WebServer: ***
Dec 03,2017 16:11:27 WebServer: WebServer: Serving HTTP on 192.168.1.29 port 80.
Dec 03,2017 16:11:27 WebServer: ***
Dec 03,2017 16:11:27 WebServer: Started
Dec 03,2017 16:11:27 WebServer: ***
Dec 03,2017 16:11:27 WebServer: WebServer: Serving HTTPS on 192.168.1.29 port 443.
Dec 03,2017 16:11:27 WebServer: ***
Dec 03,2017 16:11:33 PlexAPI: ***
Dec 03,2017 16:11:33 PlexAPI: poke plex.tv - request Plex Media Server list
Dec 03,2017 16:11:33 PlexAPI: ***
Dec 03,2017 16:11:34 PlexAPI: poke Plex-Revo (09cfca55fcab5dd0bfc933e70aeecb3a589446ee) at https://192-168-1-29.8be68320953d40ed92b7a8d29df26481.plex.direct:32400
Dec 03,2017 16:11:34 PlexAPI: No Response from Plex Media Server
Dec 03,2017 16:11:34 PlexAPI: We failed to reach a server. Reason: [Errno -5] No address associated with hostname
Dec 03,2017 16:11:34 PlexAPI: Traceback:
Traceback (most recent call last):
  File "/home/main/PlexConnect/PlexAPI.py", line 432, in getXMLFromPMS
    response = urllib2.urlopen(request, timeout=20)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -5] No address associated with hostname>

Dec 03,2017 16:11:34 PlexAPI: Servers (local, plex.tv, MyPlex): 1
Dec 03,2017 16:12:14 PlexAPI: ***
Dec 03,2017 16:12:14 PlexAPI: poke plex.tv - request Plex Media Server list
Dec 03,2017 16:12:14 PlexAPI: ***
Dec 03,2017 16:12:14 PlexAPI: poke Plex-Revo (09cfca55fcab5dd0bfc933e70aeecb3a589446ee) at https://192-168-1-29.8be68320953d40ed92b7a8d29df26481.plex.direct:32400
Dec 03,2017 16:12:14 PlexAPI: No Response from Plex Media Server
Dec 03,2017 16:12:14 PlexAPI: We failed to reach a server. Reason: [Errno -5] No address associated with hostname
Dec 03,2017 16:12:14 PlexAPI: Traceback:
Traceback (most recent call last):
  File "/home/main/PlexConnect/PlexAPI.py", line 432, in getXMLFromPMS
    response = urllib2.urlopen(request, timeout=20)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -5] No address associated with hostname>

Dec 03,2017 16:12:14 PlexAPI: Servers (local, plex.tv, MyPlex): 1
```

**Comment by moodyblue** [comment]
Pls read the [FAQ](https://forums.plex.tv/discussion/292166/plexconnect-support) in the forum.
