### ISSUE TITLE
An error occurred loading this content

### ISSUE THREAD

**Issue by Gator8** [iBaa/PlexConnect#533]
22:35:48 WebServer: Internal Server Error:
Traceback (most recent call last):
  File "/volume1/@appstore/plexconnect/share/PlexConnect/WebServer.py", line 229, in do_GET
    XML = XMLConverter.XML_PMS2aTV(PMSaddress, self.path + query, options)
  File "/volume1/@appstore/plexconnect/share/PlexConnect/XMLConverter.py", line 382, in XML_PMS2aTV
    PMS = PlexAPI.getXMLFromPMS(PMS_baseURL, path, options, auth_token, enableGzip)
  File "/volume1/@appstore/plexconnect/share/PlexConnect/PlexAPI.py", line 426, in getXMLFromPMS
    response = urllib2.urlopen(request, timeout=20)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 421, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: /library/metadata/6629

**Comment by vnuEndru** [comment]
Same problem, any solutions?

**Comment by vnuEndru** [comment]
@Gator8 [installing v0.6](https://forums.plex.tv/discussion/309983/plexconnect-v0-6-has-been-released) works for me
