### ISSUE TITLE
Cannot access Plex - Server discovery is broken

### ISSUE THREAD

**Issue by rcarmo** [iBaa/PlexConnect#534]
Hi there,

I keep having random trouble using PlexConnect. Either it fails to reach the servers even though it detects them automatically:

```
plexconnect      | Apr 21,2018 11:53:24 PlexAPI: Servers (local, plex.tv, MyPlex): 3
plexconnect      | Apr 21,2018 11:53:44 PlexAPI: No Response from Plex Media Server
plexconnect      | Apr 21,2018 11:53:44 PlexAPI: We failed to reach a server. Reason: timed out
plexconnect      | Apr 21,2018 11:53:44 PlexAPI: Traceback:
plexconnect      | Traceback (most recent call last):
plexconnect      |   File "/app/plexconnect/PlexAPI.py", line 438, in getXMLFromPMS
plexconnect      |     response = urllib2.urlopen(request, timeout=20)
plexconnect      |   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
plexconnect      |     return opener.open(url, data, timeout)
plexconnect      |   File "/usr/lib/python2.7/urllib2.py", line 429, in open
plexconnect      |     response = self._open(req, data)
plexconnect      |   File "/usr/lib/python2.7/urllib2.py", line 447, in _open
plexconnect      |     '_open', req)
plexconnect      |   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
plexconnect      |     result = func(*args)
plexconnect      |   File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
plexconnect      |     context=self._context)
plexconnect      |   File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
plexconnect      |     raise URLError(err)
plexconnect      | URLError: <urlopen error timed out>
```

...or it appears to reach one of them and then fails to process the URLs:

```
plexconnect      | Apr 21,2018 11:54:43 WebServer: serving .xml: /library/sections/2/recentlyAdded
plexconnect      | Apr 21,2018 11:54:43 WebServer: Internal Server Error:
plexconnect      | Traceback (most recent call last):
plexconnect      |   File "/app/plexconnect/WebServer.py", line 244, in do_GET
plexconnect      |     XML = XMLConverter.XML_PMS2aTV(PMSaddress, self.path + query, options)
plexconnect      |   File "/app/plexconnect/XMLConverter.py", line 382, in XML_PMS2aTV
plexconnect      |     PMS = PlexAPI.getXMLFromPMS(PMS_baseURL, path, options, auth_token, enableGzip)
plexconnect      |   File "/app/plexconnect/PlexAPI.py", line 438, in getXMLFromPMS
plexconnect      |     response = urllib2.urlopen(request, timeout=20)
plexconnect      |   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
plexconnect      |     return opener.open(url, data, timeout)
plexconnect      |   File "/usr/lib/python2.7/urllib2.py", line 421, in open
plexconnect      |     protocol = req.get_type()
plexconnect      |   File "/usr/lib/python2.7/urllib2.py", line 283, in get_type
plexconnect      |     raise ValueError, "unknown url type: %s" % self.__original
plexconnect      | ValueError: unknown url type: /library/sections/2/recentlyAdded?stack=1&X-Plex-Container-Start=0&X-Plex-Container-Size=20
```

I've yet to figure out what is happening, but my guess is that the new PMS releases have changed URL formats somehow (I'm running 1.12.3.4973 inside Docker, and PlexConnect also inside Docker).

Everything worked fine a month or so ago.

**Comment by rcarmo** [comment]
Dug a little further into this:

```
Apr 21,2018 12:03:06 PlexAPI: ***
Apr 21,2018 12:03:06 PlexAPI: poke plex.tv - request Plex Media Server list
Apr 21,2018 12:03:06 PlexAPI: ***
Apr 21,2018 12:03:06 PlexAPI: poke server1 (b217710432551fd4def7aaf203266436c9cXXXXX) at https://192-168-193-88.b9a02b121981489eb5e7b2378de4769b.plex.direct:32400
Apr 21,2018 12:03:06 PlexAPI: poke server1 (b217710432551fd4def7aaf203266436c9cXXXXX) at https://172-18-0-1.b9a02b121981489eb5e7b2378de4769b.plex.direct:32400
Apr 21,2018 12:03:06 PlexAPI: poke server1 (b217710432551fd4def7aaf203266436c9cXXXXX) at https://172-17-0-1.b9a02b121981489eb5e7b2378de4769b.plex.direct:32400
Apr 21,2018 12:03:06 PlexAPI: poke server1 (b217710432551fd4def7aaf203266436c9cXXXXX) at https://172-19-0-1.b9a02b121981489eb5e7b2378de4769b.plex.direct:32400
Apr 21,2018 12:03:06 PlexAPI: poke server1 (b217710432551fd4def7aaf203266436c9cXXXXX) at https://192-168-1-100.b9a02b121981489eb5e7b2378de4769b.plex.direct:32400
Apr 21,2018 12:03:06 PlexAPI: poke server1 (b217710432551fd4def7aaf203266436c9cXXXXX) at https://148-63-89-197.b9a02b121981489eb5e7b2378de4769b.plex.direct:14760
Apr 21,2018 12:03:06 PlexAPI: poke server2 (77ed4cd29dc6abb8d5aff856ca8fb8f18d1XXXXX) at https://YYY-227-239-21.7fa91588624b45d48f0e6389ed384bb5.plex.direct:32400
Apr 21,2018 12:03:06 PlexAPI: poke server2 (77ed4cd29dc6abb8d5aff856ca8fb8f18d1XXXXX) at https://YYY-227-239-31.7fa91588624b45d48f0e6389ed384bb5.plex.direct:32400
Apr 21,2018 12:03:06 PlexAPI: poke server2 (77ed4cd29dc6abb8d5aff856ca8fb8f18d1XXXXX) at https://YYY-227-239-22.7fa91588624b45d48f0e6389ed384bb5.plex.direct:32400
Apr 21,2018 12:03:06 PlexAPI: poke server2 (77ed4cd29dc6abb8d5aff856ca8fb8f18d1XXXXX) at https://YYY-227-239-23.7fa91588624b45d48f0e6389ed384bb5.plex.direct:32400
Apr 21,2018 12:03:06 PlexAPI: poke server2 (77ed4cd29dc6abb8d5aff856ca8fb8f18d1XXXXX) at https://10-10-10-1.7fa91588624b45d48f0e6389ed384bb5.plex.direct:32400
Apr 21,2018 12:03:06 PlexAPI: poke server2 (77ed4cd29dc6abb8d5aff856ca8fb8f18d1XXXXX) at https://10-10-10-4.7fa91588624b45d48f0e6389ed384bb5.plex.direct:32400
Apr 21,2018 12:03:06 PlexAPI: poke server2 (77ed4cd29dc6abb8d5aff856ca8fb8f18d1XXXXX) at https://YYY-227-239-20.7fa91588624b45d48f0e6389ed384bb5.plex.direct:32400
Apr 21,2018 12:03:07 PlexAPI: response server1 (b217710432551fd4def7aaf203266436c9cXXXXX) at https://192-168-193-88.b9a02b121981489eb5e7b2378de4769b.plex.direct:32400
Apr 21,2018 12:03:07 PlexAPI: response server2 (77ed4cd29dc6abb8d5aff856ca8fb8f18d1XXXXX) at https://YYY-227-239-21.7fa91588624b45d48f0e6389ed384bb5.plex.direct:32400
```

As it turns out, PlexConnect is selecting the _wrong_ addresses for the servers. Regardless of whatever I do, and however the servers are configured, it is picking the wrong alias from Plex's resolver and cannot access either server.

I've tried disabling discovery and setting the IP in the config file, but it _always_ fails to pick the right IP address for some reason.

**Comment by vnuEndru** [comment]
Same problem, any solutions?

**Comment by Kromatic3** [comment]
Same problem here as well. Any news on this issue?

**Comment by vnuEndru** [comment]
@Kromatic3  [installing v0.6](https://forums.plex.tv/discussion/309983/plexconnect-v0-6-has-been-released) works for me

**Comment by maxrugen** [comment]
Same problem. PlexConnect seems to notice my server but timeouts while connecting. 

I set up my Plex Media Server in the `Settings.cfg` file under `ip_pms` but I just can't get it to work correctly.

Please, provide a fix :(

```
Jul 15,2018 13:37:30 PlexAPI: ***
Jul 15,2018 13:37:30 PlexAPI: poke plex.tv - request Plex Media Server list
Jul 15,2018 13:37:30 PlexAPI: ***
Jul 15,2018 13:37:30 PlexAPI: poke rugel-nas (a53e7edf0801fe809714ff4c4514a5ff20a4ba8b) at https://192-168-178-99.06974280d5e34ce6989848bb755eca6d.plex.direct:32400
Jul 15,2018 13:37:30 PlexAPI: poke rugel-nas (a53e7edf0801fe809714ff4c4514a5ff20a4ba8b) at https://172-17-42-1.06974280d5e34ce6989848bb755eca6d.plex.direct:32400
Jul 15,2018 13:37:52 PlexAPI: No Response from Plex Media Server
Jul 15,2018 13:37:52 PlexAPI: We failed to reach a server. Reason: timed out
Jul 15,2018 13:37:52 PlexAPI: Traceback:
Traceback (most recent call last):
  File "/Applications/PlexConnect-master/PlexAPI.py", line 441, in getXMLFromPMS
    response = urllib2.urlopen(request, timeout=20)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>

Jul 15,2018 13:38:00 PlexAPI: No Response from Plex Media Server
Jul 15,2018 13:38:00 PlexAPI: We failed to reach a server. Reason: [Errno 8] nodename nor servname provided, or not known
Jul 15,2018 13:38:00 PlexAPI: Traceback:
Traceback (most recent call last):
  File "/Applications/PlexConnect-master/PlexAPI.py", line 441, in getXMLFromPMS
    response = urllib2.urlopen(request, timeout=20)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

Jul 15,2018 13:38:00 PlexAPI: Servers (local, plex.tv, MyPlex): 1
Jul 15,2018 13:38:00 WebServer: serving .xml: /PlexConnect.xml
Jul 15,2018 13:38:00 WebServer: serving /js/utils.js
Jul 15,2018 13:38:00 WebServer: serving /js/handlePlexConnectNavbar.js
Jul 15,2018 13:38:01 WebServer: serving .xml: /library/sections
Jul 15,2018 13:38:01 WebServer: serving /js/utils.js
Jul 15,2018 13:38:01 WebServer: serving /js/sectionHoldSelect.js
```

**Comment by Fish2** [comment]
what version are you using ?

**Comment by maxrugen** [comment]
PlexConnect version 0.6, Plex Media Server Version 1.13.2.5154 running on a WD My Cloud EX2 Ultra.

**Comment by Fish2** [comment]
ok have you tried setting enable_plexgdm to false then I till use the ip you have inputed on ip_pms all make sure port_pms is right as well

**Comment by maxrugen** [comment]
Doesn't quite change anything.

This is the output:

```
Jul 16,2018 12:20:50 WebServer: serving /js/application.js
Jul 16,2018 12:20:50 WebServer: serving .xml: /
Jul 16,2018 12:20:50 PlexAPI: ***
Jul 16,2018 12:20:50 PlexAPI: poke plex.tv - request Plex Media Server list
Jul 16,2018 12:20:50 PlexAPI: ***
Jul 16,2018 12:20:50 PlexAPI: poke rugel-nas (a53e7edf0801fe809714ff4c4514a5ff20a4ba8b) at https://192-168-178-99.06974280d5e34ce6989848bb755eca6d.plex.direct:32400
Jul 16,2018 12:20:50 PlexAPI: poke rugel-nas (a53e7edf0801fe809714ff4c4514a5ff20a4ba8b) at https://172-17-42-1.06974280d5e34ce6989848bb755eca6d.plex.direct:32400
Jul 16,2018 12:21:10 PlexAPI: No Response from Plex Media Server
Jul 16,2018 12:21:10 PlexAPI: We failed to reach a server. Reason: timed out
Jul 16,2018 12:21:10 PlexAPI: Traceback:
Traceback (most recent call last):
  File "/Applications/PlexConnect-master/PlexAPI.py", line 441, in getXMLFromPMS
    response = urllib2.urlopen(request, timeout=20)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>

Jul 16,2018 12:21:20 PlexAPI: No Response from Plex Media Server
Jul 16,2018 12:21:20 PlexAPI: We failed to reach a server. Reason: [Errno 8] nodename nor servname provided, or not known
Jul 16,2018 12:21:20 PlexAPI: Traceback:
Traceback (most recent call last):
  File "/Applications/PlexConnect-master/PlexAPI.py", line 441, in getXMLFromPMS
    response = urllib2.urlopen(request, timeout=20)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>

Jul 16,2018 12:21:20 PlexAPI: Servers (local, plex.tv, MyPlex): 1
Jul 16,2018 12:21:20 WebServer: serving .xml: /PlexConnect.xml
Jul 16,2018 12:21:21 WebServer: serving /js/utils.js
Jul 16,2018 12:21:21 WebServer: serving /js/handlePlexConnectNavbar.js
Jul 16,2018 12:21:21 WebServer: serving .xml: /library/sections
Jul 16,2018 12:21:21 WebServer: serving /js/utils.js
Jul 16,2018 12:21:21 WebServer: serving /js/sectionHoldSelect.js
```



My `Settings.cfg` looks like this:

```
[PlexConnect]
enable_plexgdm = False
ip_pms = 192.168.178.99
port_pms = 32400
enable_dnsserver = True
port_dnsserver = 53
ip_dnsmaster = 8.8.8.8
prevent_atv_update = True
intercept_atv_icon = True
enable_plexconnect_autodetect = True
ip_plexconnect = 0.0.0.0
use_custom_dns_bind_ip = False
custom_dns_bind_ip = 0.0.0.0
hosttointercept = trailers.apple.com
icon = movie-trailers
certfile = ./assets/certificates/trailers.pem
port_webserver = 80
enable_webserver_ssl = True
port_ssl = 443
allow_gzip_atv = False
allow_gzip_pmslocal = False
allow_gzip_pmsremote = True
fanart_quality = High
loglevel = Normal
logpath = .
```

Maybe something's wrong in there?

**Comment by moodyblue** [comment]
Seems to be a PMS problem, not a PlexConnect problem. Pls report in the Plex forum. I will need PMS logs with the initialization sequence (when PMS boots).

**Comment by moodyblue** [comment]
Anyhow I've updated the server discovery criteria, please test
