### ISSUE TITLE
Can't sign in Plex

### ISSUE THREAD

**Issue by nmhung1985** [iBaa/PlexConnect#546]
Hi, 

I installed PlexConnect on my Asus router using the Tomato guide. The app can see the server only when enable_plexgdm = **False**

1. It doesn't list the videos (most were recorded from Apple iPhones).

2. I also can't sign in to Plex. After submitting username and password, it just returns to the settings menu and shows a "loading..." icon. The log shows some error regarding "SSL: CERTIFICATE_VERIFY_FAILED". 

Below is my setup info and the log. Please offer some help, thanks in advance.

My Setup:
ATV: Apple TV 3 Rev A (A1469)
Router: Asus AC68U - Using the Tomato guide, so you know, the router manages most of the thing
PMS: 1.13.9.5456 on Windows 10
Settings.cfg: 

> [PlexConnect]
> enable_plexgdm = False
> ip_pms = 192.168.5.92
> port_pms = 32400
> enable_dnsserver = False
> port_dnsserver = 53
> ip_dnsmaster = 8.8.8.8
> prevent_atv_update = True
> intercept_atv_icon = True
> enable_plexconnect_autodetect = False
> ip_plexconnect = 192.168.5.1
> use_custom_dns_bind_ip = False
> custom_dns_bind_ip = 0.0.0.0
> hosttointercept = trailers.apple.com
> icon = movie-trailers
> certfile = ./assets/certificates/trailers.pem
> port_webserver = 8080
> enable_webserver_ssl = True
> port_ssl = 8443
> allow_gzip_atv = False
> allow_gzip_pmslocal = False
> allow_gzip_pmsremote = True
> fanart_quality = High
> loglevel = Normal
> logpath = .

The log:
https://pastebin.com/LdjgDXUQ

**Comment by moodyblue** [comment]
Why are you using ports 8080 and 8443 ? ATV expects ports 80 and 443. I know that you can establish rules in Apache and Nginx to bypass this requirement but I'm not sure about Tomato firmware.

**Comment by nmhung1985** [comment]
Thanks for your answer. Sorry, when I said about "doesn't list videos", I didn't make it clear that:

Actually, I **can** browse and view the library **without** needing to sign in plex.tv and enable the LAN.

1. As I understand, doesn't that also mean using different ports works, as the router redirects/masks traffic via its firewall system, so ATV still thinks it is connecting to 80/443 while in facts the router makes it connect to 8080/8443.

2. At first I thought PlexConnect doesn't support videos (like Infuse for instance), but as I saw people said about fps issues, my question regarding videos not visible in the library was posted.

3. GDM is enabled by default and I haven't touched it. Don't know about zeroconf though, I'll check that. Anyway, it's not that important as I can specify the PMS manually.

The important thing is I'd like to sign in plex.tv. Did you take a look at my log and have any ideas what's about that SSL certificate error?

**Comment by moodyblue** [comment]
Unless you are signed in, or your LAN is authorized, you will be able to browse libraries but not see any film.

No idea about the certificate error. But another user reported, sometime ago, that ATV hour (or hour region) was causing problems.

**Comment by nmhung1985** [comment]
1. 
1a) Oh, I read the FAQ in the forum, but I overlooked it. My library has family photos mixed with family videos, so obviously PlexConnect doesn't support that library type. Tried creating a test library with videos only, and videos appeared. -> VIDEO ISSUE RESOLVED! If possible you may want to sync the FAQ here and on the forum.

1b). I tried googling the SSL error, and found some StackOverflow discussions. In general, I tried installing some more python modules/components here and there. And the sign in feature worked! -> SSL ISSUE RESOLVED!

2. **However**, there are new issues or things I may not fully understand:
2a) If the PMSes are on a remote/different network, PlexConnect wouldn't show any libraries. For testing, in the same house:
- ATV and PlexConnect are both connecting to Router A, 
- I connect two PMS to Router B. PMS 1 has one library shared to PMS 2.
(Both routers have separate subnets, are now having their WAN ports connected to the modem LAN ports)
`enable_plexgdm = _False_`: the Trailers app doesn't even load up (This is obvious, I guess, as it could never find the one defined in ip_pms).
`enable_plexgdm = True` and signing in Plex.tv: informing that no servers found, and doesn't show any libraries, even in "Shared Libraries". But the log showed that PlexConnect found those servers on Plex.tv, but got some errors "no route to host"

```
> Nov 20,2018 18:57:46 PlexAPI: ***
> Nov 20,2018 18:57:46 PlexAPI: poke plex.tv - request Plex Media Server list
> Nov 20,2018 18:57:46 PlexAPI: ***
> Nov 20,2018 18:57:47 PlexAPI: poke Dell-E5470 (af4e6e5e3a476564653684e020b5868ec1f477a0) at https://192-168-5-92.2fcea191ed4342ef8d975c3f32c4bcb8.plex.direct:32400
> Nov 20,2018 18:57:47 PlexAPI: poke DC (70628e69742b37f338cdcce125b04802e38617ea) at https://192-168-5-11.99735e74a58a41fdba893de25c4ac92c.plex.direct:32400
> Nov 20,2018 18:57:48 PlexAPI: No Response from Plex Media ServerNov 20,2018 18:57:48 PlexAPI: No Response from Plex Media Server
> Nov 20,2018 18:57:48 PlexAPI: We failed to reach a server. Reason: [Errno 113] No route to host
> Nov 20,2018 18:57:48 PlexAPI: We failed to reach a server. Reason: [Errno 113] No route to host
> Nov 20,2018 18:57:48 PlexAPI: Traceback:
> Traceback (most recent call last):
>   File "/tmp/mnt/Flair/entware/PlexConnect/PlexAPI.py", line 449, in getXMLFromPMS
>     response = urllib2.urlopen(request, timeout=20)
>   File "/opt/lib/python2.7/urllib2.py", line 154, in urlopen
>   File "/opt/lib/python2.7/urllib2.py", line 429, in open
>   File "/opt/lib/python2.7/urllib2.py", line 447, in _open
>   File "/opt/lib/python2.7/urllib2.py", line 407, in _call_chain
>   File "/opt/lib/python2.7/urllib2.py", line 1241, in https_open
>   File "/opt/lib/python2.7/urllib2.py", line 1198, in do_open
> URLError: <urlopen error [Errno 113] No route to host>
```

2b) If **two PMS**, ATV and PlexConnect are on the same network, connecting to one Router:
`enable_plexgdm = True` and NOT signing in Plex.tv: no servers found
`enable_plexgdm = True` and signing in Plex.tv: both servers found, got some HTTP Error 401: Unauthorized
`enable_plexgdm = _False_` and signing in/NOT signing in Plex.tv: only the one server defined by ip_pms found (this is by design, I think)

I'll reset the PlexConnect installation from scratch to narrow down what should be done exactly and note here for you to update the installation guide. By the way, you should link to this [better written guide](https://forums.plex.tv/t/tutorial-plexconnect-on-a-tomato-router-via-entware/95436) that I followed (instead of the old post currently linked in the wiki).

**Comment by nmhung1985** [comment]
Please disregard my previous post, I messed up my observations. Today I did another thorough test and I've posted on the forum here: [Link](https://forums.plex.tv/t/plexconnect-running-on-wrt-router-merlin-for-asus-cant-find-remote-pms/335203)
