### ISSUE TITLE
Unable to connect to Plex account using firmware 7.6 Apple TV 3 no jailbreak

### ISSUE THREAD

**Issue by raqmudy** [iBaa/PlexConnect#591]
Traceback (most recent call last):
  File "C:\Scripts\PlexConnect-master\WebServer.py", line 248, in do_GET
    XML = XMLConverter.XML_PMS2aTV(PMSaddress, self.path + query, options)
  File "C:\Scripts\PlexConnect-master\XMLConverter.py", line 249, in XML_PMS2aTV
    (username, auth_token) = PlexAPI.MyPlexSignIn(parts[0], parts[1], options)
  File "C:\Scripts\PlexConnect-master\PlexAPI.py", line 691, in MyPlexSignIn
    response = urlopener.open(request).read()
  File "C:\Python27\lib\urllib2.py", line 391, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 409, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1181, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1148, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10054] Se ha forzado la interrupci?n de una conexi?n existente por el host remoto>

**Comment by moodyblue** [comment]
User support is provided in the plex forum https://forums.plex.tv/tags/c/third-party/apps-tools/53/plexconnect

Then, if this is a bug, I will reopen this issue.
