### ISSUE TITLE
Plexconnect ATV2 v0.7.5

### ISSUE THREAD

**Issue by sojab0on** [iBaa/PlexConnect#617]
When i launch my new version of plexconnect on the atv2 (kortv) after i try to log in to plex account it gives back 
Traceback (most recent call last):
  File "C:\Program Files (x86)\PlexConnect-0.7.5\WebServer.py", line 248, in do_GET
    XML = XMLConverter.XML_PMS2aTV(PMSaddress, self.path + query, options)
  File "C:\Program Files (x86)\PlexConnect-0.7.5\XMLConverter.py", line 249, in XML_PMS2aTV
    (username, auth_token) = PlexAPI.MyPlexSignIn(parts[0], parts[1], options)
  File "C:\Program Files (x86)\PlexConnect-0.7.5\PlexAPI.py", line 694, in MyPlexSignIn
    response = urlopener.open(request).read()
  File "C:\Python27\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077458:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 unrecognized name>
in de cmd window on my pc (same as where plex server is running) 

Aug 11,2023 11:45:19 PlexConnect: PlexConnect
Aug 11,2023 11:45:19 PlexConnect: Press CTRL-C to shut down.
Aug 11,2023 11:45:19 PlexConnect: ***
Aug 11,2023 11:45:19 PlexConnect: Started
Aug 11,2023 11:45:19 PlexConnect: Version: 0.7.5-280323
Aug 11,2023 11:45:19 PlexConnect: Python: 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]
Aug 11,2023 11:45:19 PlexConnect: Host OS: win32
Aug 11,2023 11:45:19 PlexConnect: PILBackgrounds: Is PIL installed? False
Aug 11,2023 11:45:19 PlexConnect: IP_self: 172.16.0.38
Aug 11,2023 11:45:20 DNSServer: Started
Aug 11,2023 11:45:20 DNSServer: Intercept Atv Icon: Enabled
Aug 11,2023 11:45:20 DNSServer: Prevent Atv Update: Enabled
Aug 11,2023 11:45:20 DNSServer: ***
Aug 11,2023 11:45:20 DNSServer: DNSServer: Serving DNS on 172.16.0.38 port 53.
Aug 11,2023 11:45:20 DNSServer: intercept: ['kortv.com', 'a1.phobos.apple.com'] => 172.16.0.38
Aug 11,2023 11:45:20 DNSServer: restrain: ['mesu.apple.com', 'appldnld.apple.com', 'appldnld.apple.com.edgesuite.net'] => 127.0.0.1
server startup logging 
due to this i cant get to my media it detects the server but it will not show the media until i log in

**Comment by moodyblue** [comment]
Pls post your `Settings.cfg`. Also, probably, you also need to delete `ATVSettings.cfg` (close PlexConnect, delete `ATVSettings.cfg`, and start PlexConnect)
