### ISSUE TITLE
PlexConnect on M1 in 2023? - PlexConnect as a Windows Service?

### ISSUE THREAD

**Issue by mcsestak** [iBaa/PlexConnect#619]
**My New System**
Mac Mini M1: Running PlexConnect via Parallels on Virtual Install of Windows 11

**I have two (simple?) questions:** 

1) Does PlexConnect work on MacOS Sonoma?  I was under the impression it was no longer working after recent updates? Since I thought Windows was my only option, I went the virtual Windows route.

2) I've now got Plex running on virtual Windows 11, running on a Mac Mini M1. It's working great, but I can't figure out how to get the Windows Autostart to work. Back in 2016, I was able to add it as a Service for Windows. But for some reason in 2023 I can't figure it out. And it's driving me crazy. In the meantime, I've downloaded the trial of FireDaemon Pro which runs anything as a service. But soon I've have to buy it!  ;-) 

The PlexConnect Autostart instructions are here: _https://github.com/iBaa/PlexConnect/wiki/Win-autostart_ but I think I need more hand-holding on this one!  Like 5th grade level stuff maybe.

Thanks a million to anyone who can help!  @moodyblue

**Comment by moodyblue** [comment]
Hi, PlexConnect runs in any platform where python2 is available (not many options these days).

Regarding running PlexConnect as a windows service see https://github.com/iBaa/PlexConnect/wiki/Win-autostart

**Comment by mcsestak** [comment]
Trying to install in MaxOS.  I follow all the steps - installed Python 2.7.9 - added cert. But ATV cannot login to Plex Media Server.  I get this:


Oct 30,2023 21:51:16 PlexAPI: PlexGDM - looking up Plex Media Server
Oct 30,2023 21:51:16 PlexAPI: ***
Oct 30,2023 21:51:17 PlexAPI: GDM: Servers discovered: 1
Oct 30,2023 21:51:17 PlexAPI: Plex Media Servers found: 1
Oct 30,2023 21:51:17 WebServer: serving .xml: /
Oct 30,2023 21:51:24 WebServer: serving .xml: /PlexConnect.xml
Oct 30,2023 21:51:32 WebServer: serving .xml: /
 Oct 30,2023 21:51:32 WebServer: serving .xml: /PlexConnect.xml
Oct 30,2023 21:51:33 WebServer: File Not Found:
Traceback (most recent call last):
  File "/Applications/PlexConnect/WebServer.py", line 248, in do_GET
    XML = XMLConverter.XML_PMS2aTV(PMSaddress, self.path + query, options)
  File "/Applications/PlexConnect/XMLConverter.py", line 249, in XML_PMS2aTV
    (username, auth_token) = PlexAPI.MyPlexSignIn(parts[0], parts[1], options)
  File "/Applications/PlexConnect/PlexAPI.py", line 694, in MyPlexSignIn
    response = urlopener.open(request).read()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:581)>
